### ISSUE TITLE
Bring Back Embedded Message Previews

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#433]
ClemBot used to support the ability to generate embedded previews of links to existing messages. I propose bringing back this functionality by letting server managers opt-in to this feature on a server-by-server basis. This would resolve the reason it was removed since some servers didn't want ClemBot doing this for posted links.

**Comment by Jay-Madden** [comment]
The functionality wasn't removed, just disabled due to the fact it couldn't be turned off and it bothered some servers. one of the first things that will happen when we get the dashboard up and running is we will add a toggle on the site

https://github.com/ClemBotProject/ClemBot/blob/8524dc572b4eafacbe772ea2976b7a8c081cba15/ClemBot.Bot/bot/services/message_handling_service.py#L94

We could in the meantime add a command that embeds it, like !link or something. i would accept a pr for that

**Comment by smathep** [comment]
@Jay-Madden shouldn't this be closed?
